name = "BridgesCA"
uuid = "702f4781-cb57-437e-b371-49fdc22f8a58"
authors = ["jarupas"]
version = "1.0.0-DEV"

[compat]
julia = "1.11.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
